/*
 * File: app/model/Note.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NotesApp.model.Note', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'Id',
                type: 'int'
            },
            {
                dateFormat: 'c',
                name: 'dateCreated',
                type: 'date'
            },
            {
                name: 'tittle',
                type: 'string'
            },
            {
                name: 'narrative',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'presence',
                field: 'id'
            },
            {
                type: 'presence',
                field: 'dateCreated'
            },
            {
                type: 'presence',
                message: 'Please enter a title for this note.',
                field: 'tiitle'
            }
        ]
    }
});