/*
 * File: app/controller/Notes.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NotesApp.controller.Notes', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            notesListContainer: 'noteslistcontainer',
            noteEditore: {
                autoCreate: true,
                selector: 'noteeditor',
                xtype: 'noteeditor'
            }
        },

        control: {
            "notesListContainer": {
                newNoteCommand: 'onNewNoteCommand',
                editNoteCommand: 'onEditNoteCommand'
            }
        }
    },

    onNewNoteCommand: function(container) {
            console.log("onNewNoteCommand");

            var now = new Date();
            var noteId = (now.getTime()).toString() + (this.getRandomInt(0, 100)).toString();

            var newNote = Ext.create("NotesApp.model.Note", {
                id: noteId,
                dateCreated: now,
                title: "",
                narrative: ""
            });

            this.activateNoteEditor(newNote);
    },

    onEditNoteCommand: function(container) {

    },

    launch: function() {
        this.callParent(arguments);
        Ext.getStore('localExampleStore').load();
        console.log("launch");

    },

    getRandomInt: function(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    },

    activateNoteEditor: function(record) {
        var noteEditor = this.getNoteEditore();

        noteEditor.setRecord(record); // load() is deprecated.
        Ext.Viewport.animateActiveItem(noteEditor, this.slideLeftTransition);
    },

    init: function(application) {
        this.slideLeftTransition = { type: 'slide', direction: 'left' };

    }

});