/*
 * File: app/view/NotesListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NotesApp.view.NotesListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.noteslistcontainer',

    config: {
        layout: {
            type: 'fit'
        }
    },

    initialize: function() {
        this.callParent();

        var newButton = {
            xtype: "button",
            text: 'New',
            ui: 'action',
            handler: this.onNewButtonTap,
            scope: this
        };

        var topToolbar = {
            xtype: "toolbar",
            title: 'My Notes',
            docked: "top",
            items: [
            { xtype: 'spacer' },
            newButton
            ]
        };

        var notesList = {
            xtype: "noteslist",
            store: Ext.getStore('localExampleStore'),
            listeners: {
                disclose: { fn: this.onNotesListDisclose, scope: this }
            }
        };

        this.add([topToolbar, notesList]);
    },

    onNewButtonTap: function() {
        console.log("newNoteCommand");
        this.fireEvent("newNoteCommand", this);
    },

    onNotesListDisclose: function(list, record, target, index, evt, options) {
        console.log("editNoteCommand");
        this.fireEvent('editNoteCommand', this, record);

    }

});