/*
 * File: app/store/Notes.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NotesApp.store.Notes', {
    extend: 'Ext.data.Store',

    requires: [
        'NotesApp.model.Note',
        'Ext.util.Sorter'
    ],

    config: {
        data: [
            {
                title: 'Note 1',
                narrative: 'narrative 1'
            },
            {
                title: 'Note 2',
                narrative: 'narrative 2'
            },
            {
                title: 'Note 3',
                narrative: 'narrative 3'
            },
            {
                title: 'Note 4',
                narrative: 'narrative 4'
            },
            {
                title: 'Note 5',
                narrative: 'narrative 5'
            },
            {
                title: 'Note 6',
                narrative: 'narrative 6'
            }
        ],
        model: 'NotesApp.model.Note',
        storeId: 'localExampleStore',
        sorters: {
            direction: 'DESC',
            property: 'dateCreated'
        }
    }
});